// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHUeffF4fG189RD6LzSrHkO0mKlVxCYNA',
    appId: '1:676982411224:web:ecc215fbb03898d3d82cad',
    messagingSenderId: '676982411224',
    projectId: 'safteynet-46fa0',
    authDomain: 'safteynet-46fa0.firebaseapp.com',
    storageBucket: 'safteynet-46fa0.firebasestorage.app',
    measurementId: 'G-G93NH8RCTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf327n8b-8Ai_4_4S67kiJj6DXDADeZFw',
    appId: '1:676982411224:android:3b1aa6e304df830fd82cad',
    messagingSenderId: '676982411224',
    projectId: 'safteynet-46fa0',
    storageBucket: 'safteynet-46fa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3YeX5Wx1l3C3NlDUd0VXHWcyiRqpHKmA',
    appId: '1:676982411224:ios:cd8240a5608f51d8d82cad',
    messagingSenderId: '676982411224',
    projectId: 'safteynet-46fa0',
    storageBucket: 'safteynet-46fa0.firebasestorage.app',
    iosBundleId: 'com.example.safteyNet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3YeX5Wx1l3C3NlDUd0VXHWcyiRqpHKmA',
    appId: '1:676982411224:ios:cd8240a5608f51d8d82cad',
    messagingSenderId: '676982411224',
    projectId: 'safteynet-46fa0',
    storageBucket: 'safteynet-46fa0.firebasestorage.app',
    iosBundleId: 'com.example.safteyNet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHUeffF4fG189RD6LzSrHkO0mKlVxCYNA',
    appId: '1:676982411224:web:9be2e662428d1b7ad82cad',
    messagingSenderId: '676982411224',
    projectId: 'safteynet-46fa0',
    authDomain: 'safteynet-46fa0.firebaseapp.com',
    storageBucket: 'safteynet-46fa0.firebasestorage.app',
    measurementId: 'G-N0CR8PTGDN',
  );
}
